---
worlds: [world]
# Which worlds should you allow this plugin to function on - world has set as a default world. You can edit it whenever you want.

money: 100
# Player money - How much money should you get when you kill a victim? Default: $150

mob-money: 50
# How much money should you get when you kill a mob? Default: $1

messages:
 enable: true
 # Allows messages to be turned on. Highly recommend to turn on for better gameplay.
 
 message: "§a§l(PLAYERKILL)&r §3You have earned §b%MONEY% §6for killing §e%PLAYER%"
 # Player kill message, sent to the killer.

 mobmessage: "§e§l(MOBKILL)§r §6You have earned §e%MOB_MONEY% §6for killing §e%MOB%"
 # Mob kill message, sent to the killer.
...
